export const USER_LOGIN_ERROR = "USE_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";